#!/usr/bin/env python3
"""
server — minimal FastAPI backend for the House Hunter dashboard.

Serves the static `results.html` dashboard (generated by `scripts/templates.py`)
and exposes two AJAX endpoints so Tiago can approve/reject listings straight
from the browser. Verdicts are written back to `data/house_state.json` so the
validation agent's decisions and Tiago's manual feedback can be compared later
to improve the agent's prompt.

Usage (standalone):
  python scripts/server.py

Usage (from house_hunter.py --web):
  from server import app, serve_and_open
  serve_and_open(app)
"""

from __future__ import annotations

import json
import sys
import threading
import webbrowser
from datetime import datetime, timezone
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

try:
    import uvicorn
    from fastapi import FastAPI, HTTPException
    from fastapi.middleware.cors import CORSMiddleware
    from fastapi.responses import HTMLResponse
    from pydantic import BaseModel
except ImportError:
    sys.exit(
        "ERROR: fastapi/uvicorn not installed. Run: pip install fastapi uvicorn"
    )

REPO_ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = REPO_ROOT / "data" / "house_state.json"
RESULTS_HTML_PATH = REPO_ROOT / "results.html"

FALLBACK_HTML = (
    "<!doctype html><html><body style='font-family: sans-serif; padding: 2rem;'>"
    "<h1>Dashboard not generated yet...</h1>"
    "<p>Run <code>python scripts/house_hunter.py --web</code> to scrape and "
    "generate the dashboard.</p>"
    "</body></html>"
)


# ---------------------------------------------------------------------------
# State (load/save house_state.json)
# ---------------------------------------------------------------------------

def load_state(path: Path = STATE_PATH) -> dict:
    """Read house_state.json → dict. Returns {} if missing or unparsable."""
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_state(state: dict, path: Path = STATE_PATH) -> None:
    """Write state dict back to path as JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class FeedbackRequest(BaseModel):
    """Body for POST /approve and POST /reject."""
    listing_id: str
    search_name: str


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def create_app(state_path: Path = STATE_PATH) -> FastAPI:
    """Create and configure FastAPI app."""
    app = FastAPI(title="House Hunter Dashboard")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Stashed on app.state so tests can point at a scratch state/results file
    # without touching the real repo files.
    app.state.state_path = state_path
    app.state.results_html_path = RESULTS_HTML_PATH

    def _set_feedback(payload: FeedbackRequest, feedback: str) -> dict:
        state = load_state(app.state.state_path)
        search = state.get(payload.search_name)
        listing = search.get(payload.listing_id) if isinstance(search, dict) else None
        if listing is None:
            raise HTTPException(
                status_code=404,
                detail=f"listing {payload.listing_id!r} not found in search {payload.search_name!r}",
            )
        listing["user_feedback"] = feedback
        listing["last_feedback"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        save_state(state, app.state.state_path)
        return {"success": True, "listing_id": payload.listing_id, "user_feedback": feedback}

    @app.get("/results", response_class=HTMLResponse)
    def get_results() -> HTMLResponse:
        html_path = app.state.results_html_path
        if html_path.exists():
            return HTMLResponse(content=html_path.read_text(encoding="utf-8"))
        return HTMLResponse(content=FALLBACK_HTML)

    @app.post("/approve")
    def approve(payload: FeedbackRequest) -> dict:
        return _set_feedback(payload, "approved")

    @app.post("/reject")
    def reject(payload: FeedbackRequest) -> dict:
        return _set_feedback(payload, "rejected")

    return app


# Module-level app instance — `house_hunter.py --web` does
# `from server import app, serve_and_open`.
app = create_app()


# ---------------------------------------------------------------------------
# Server runner
# ---------------------------------------------------------------------------

def serve_and_open(app: FastAPI, host: str = "127.0.0.1", port: int = 5000) -> None:
    """Start server and open browser."""
    url = f"http://localhost:{port}/results"

    def _open_browser() -> None:
        webbrowser.open(url)

    # Give uvicorn a moment to bind the port before the browser hits it.
    threading.Timer(1.0, _open_browser).start()
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    serve_and_open(app)
